import subprocess
import keyboard
import os
import webbrowser
import requests
from pathlib import Path

# Ollama API endpoint
OLLAMA_API_URL = "http://localhost:11434/api/generate"

# Global dictionaries to store opened process handles
opened_apps = {}
opened_urls = {}

def stop_music():
    keyboard.send("play/pause media")
    print("Toggled media playback (stop).")

def start_music():
    keyboard.send("play/pause media")
    print("Toggled media playback (start).")

def translate_text():
    """
    Capture the screen, perform OCR to extract text, and use Ollama to translate it.
    """
    try:
        import pyautogui
        import pytesseract
        from langdetect import detect, DetectorFactory
    except ImportError:
        print("Required packages not installed. Please install: pyautogui, pytesseract, langdetect")
        return

    DetectorFactory.seed = 0
    screenshot = pyautogui.screenshot()
    extracted_text = pytesseract.image_to_string(screenshot)
    
    if not extracted_text.strip():
        print("No text found on screen.")
        return

    try:
        detected_lang = detect(extracted_text)
        print(f"Detected language: {detected_lang}")
    except Exception as e:
        detected_lang = "unknown"
        print("Error detecting language:", e)

    if detected_lang == "en":
        print("The screen text appears to be in English.")
        return

    # Call Ollama for translation
    prompt = f"Translate this text to English: {extracted_text.strip()}"
    headers = {"Content-Type": "application/json"}
    data = {
        "model": "llama2",  # You can change this to your preferred model
        "prompt": prompt,
        "stream": False
    }

    try:
        response = requests.post(OLLAMA_API_URL, headers=headers, json=data)
        if response.status_code == 200:
            translation = response.json().get("response", "")
            print("\nTranslation:")
            print(translation)
        else:
            print(f"Translation Error: {response.text}")
    except requests.exceptions.RequestException as e:
        print(f"Error calling Ollama API: {e}")

def copy_neural_network_diagram():
    print("Copying neural network diagram from screen... (feature not yet implemented)")

def create_new_file():
    filename = "new_file.py"
    content = "# New Python file generated by Hey Miso\n\nprint('Hello from Hey Miso!')\n"
    try:
        with open(filename, "w") as f:
            f.write(content)
        if os.name == 'nt':  # Windows
            subprocess.run(["code", filename], check=True)
        else:  # Linux/Mac
            subprocess.run(["code", filename], check=True)
        print(f"Created and opened {filename} in VS Code.")
    except Exception as e:
        print("Error creating/opening file:", e)

def open_app():
    app_path = input("Enter application path or name: ").strip()
    if not app_path:
        print("No application specified.")
        return
    
    try:
        proc = subprocess.Popen(app_path, shell=True)
        opened_apps[app_path] = proc
        print(f"Opened application: {app_path}")
    except Exception as e:
        print(f"Error opening application: {e}")

def close_app():
    app_name = input("Enter application name to close: ").strip()
    if not app_name:
        print("No application specified.")
        return
    
    proc = opened_apps.get(app_name)
    if proc:
        proc.terminate()
        proc.wait()
        print(f"Closed application: {app_name}")
        del opened_apps[app_name]
    else:
        print("Application not found among open apps.")

def open_url():
    url = input("Enter URL to open: ").strip()
    if not url:
        print("No URL specified.")
        return
    
    # Fuzzy processing: if url doesn't start with http:// or https://, attempt to complete it
    if not (url.startswith("http://") or url.startswith("https://")):
        url = url.replace(" ", "")
        if "." not in url:
            url += ".com"
        url = "https://www." + url
    
    try:
        # Try to open with default browser
        webbrowser.open(url)
        print(f"Opened URL: {url}")
    except Exception as e:
        print(f"Error opening URL: {e}")

def close_url():
    url = input("Enter URL to close: ").strip()
    if not url:
        print("No URL specified.")
        return
    
    if not (url.startswith("http://") or url.startswith("https://")):
        url = url.replace(" ", "")
        if "." not in url:
            url += ".com"
        url = "https://www." + url
    
    proc = opened_urls.get(url)
    if proc:
        proc.terminate()
        proc.wait()
        print(f"Closed URL: {url}")
        del opened_urls[url]
    else:
        print("URL process not found.")